name: Build python package, create github release and publish to pypi

on:
  workflow_call:

jobs:
  build_and_publish:
    uses: sensirion/.github/.github/workflows/shared.python.pypi_publish.yml@main
    with:
      use-driver-index: false
    secrets: inherit
